package overview

import (
	"bytes"
	"encoding/json"
	"fmt"
)

type AutoGenerated struct {
	Overview struct {
		Description       string            `json:"description"`
		Benefits          string            `json:"benefits"`
		Requirement       string            `json:"requirement"`
		DeployDescription string            `json:"deployDescription"`
		Links             map[string]string `json:"links"`
	} `json:"overview"`
	FAQ []struct {
		Question string `json:"question"`
		Answer   string `json:"answer"`
	} `json:"FAQ"`
}

func (conf *AutoGenerated) String() string {
	b, err := json.Marshal(*conf)
	if err != nil {
		return fmt.Sprintf("%+v", *conf)
	}
	var out bytes.Buffer
	err = json.Indent(&out, b, "", "    ")
	if err != nil {
		return fmt.Sprintf("%+v", *conf)
	}
	return out.String()
}