package handle

import (
	"fmt"
	"github.com/Ankr-network/dccn-tools/parse-overview/utils/overview"
	"github.com/ghodss/yaml"
	"io/ioutil"
)

func ParseOverview(file string) error {
	out := overview.AutoGenerated{}
	buf, err := ioutil.ReadFile(file)
	if err != nil {
		return err
	}

	err = yaml.Unmarshal(buf, &out)
	if err != nil {
		return err
	}

	fmt.Println(out.String())
	return nil
}
